AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda function for image upload and analysis

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Amz-Security-Token,X-Amz-User-Agent'"
      AllowOrigin: "'*'"

Resources:
  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
    
      CodeUri: src/uploadImage/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref UploadImageBucket
          TABLE_NAME: !Ref UploadImageTable
      Events:
        # POST /items — image upload + AI analysis
        UploadImageApi:
          Type: Api
          Properties:
            Path: /items
            Method: post
        # GET /records — fetch user's records from DynamoDB
        GetRecordsApi:
          Type: Api
          Properties:
            Path: /records
            Method: get
        # GET /records/{id} — fetch single record with signed URLs
        GetSingleRecordApi:
          Type: Api
          Properties:
            Path: /records/{id}
            Method: get
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref UploadImageBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref UploadImageTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"

  UploadImageBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  UploadImageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    DeletionPolicy: Delete

Outputs:
  UploadImageApi:
    Description: "API Gateway endpoint URL for image upload"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items/"
  GetRecordsApi:
    Description: "API Gateway endpoint URL for fetching records"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/records/"
  GetSingleRecordApi:
    Description: "API Gateway endpoint URL for fetching single record"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/records/{id}/"
  UploadImageFunction:
    Description: "Upload Image Lambda Function ARN"
    Value: !GetAtt UploadImageFunction.Arn
  UploadImageBucket:
    Description: "S3 bucket for uploaded images and analysis results"
    Value: !Ref UploadImageBucket
  UploadImageTable:
    Description: "DynamoDB table for upload metadata"
    Value: !Ref UploadImageTable
